version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: SklepDotnet
    environment:
      POSTGRES_USER: sklep1
      POSTGRES_PASSWORD: sklep1
      POSTGRES_DB: sklep
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: